// config/named.conf
options {
    directory "/var/cache/bind";
    allow-query { any; };
    forwarders {
        8.8.8.8;
        1.1.1.1;
    };
    recursion yes;
};

zone "sandbox.lan" {
    type master;
    file "/etc/bind/db.sandbox.lan";
};
